# Site settings
title: American Prayer Team
email: apt@example.com
description: >
  American Prayer Team landing page
baseurl: ""
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
  biographies:
    output: true
  conx2share:
    output: false